# Generated by Django 4.2 on 2024-12-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
    ]
